(ns tamaki.observer.build-css
  (:require [css.build :as css]))

(def source "src/tamaki/observer/style.cljs")
(def output "dist/style.css")

(defn write! []
  (css/write!
   {:sheet {:rules {"html, body" {:margin 0 :width "100%" :height "100%"
                                  :overflow :hidden :background "#090611"}}
            :keyframes
            {:tamaki-pulse
             [[0 {:opacity 0.9
                  :transform "translate(-50%,-50%) scale(.25)"}]
              [100 {:opacity 0
                    :transform "translate(-50%,-50%) scale(2.8)"}]]}}
    :shadow-sources [source]
    :strict-utilities? true
    :minify? false
    :banner "Generated by kotoba-lang/css; do not edit."
    :outputs [output]}))

(defn hook
  {:shadow.build/stage :compile-finish}
  [build-state & _]
  (write!)
  build-state)

(defn -main [& _]
  (prn (select-keys (write!) [:outputs :bytes :warnings])))
