(ns tamaki.observer.build-css
  (:require [clojure.java.io :as io]
            [css.build :as css]
            [jp-go-dds.tokens :as tokens]))

(def source "src/tamaki/observer/style.cljs")
(def output "dist/style.css")
(def generated-output "dist/style.generated.css")

(defn- resource-text [path]
  (if-let [resource (io/resource path)]
    (slurp resource)
    (throw (ex-info "Required design-system resource is missing"
                    {:resource path}))))

(defn write! []
  (let [result
        (css/write!
         {:sheet {:rules {"html, body" {:margin 0 :width "100%" :height "100%"
                                        :overflow :hidden
                                        :background
                                        "var(--color-neutral-solid-gray-50)"}}
                  :keyframes
                  {:tamaki-pulse
                   [[0 {:opacity 0.9
                        :transform "translate(-50%,-50%) scale(.25)"}]
                    [100 {:opacity 0
                          :transform "translate(-50%,-50%) scale(2.8)"}]]}}
          :shadow-sources [source]
          :strict-utilities? true
          :minify? false
          :banner "Generated by kotoba-lang/css; do not edit."
          :outputs [generated-output]})
        app-css (slurp generated-output)
        design-css (resource-text "jp_go_dds/dds.css")]
    (spit output
          (str "/* DADS vendored by kotoba-lang/jp-go-digital-design-system. */\n"
               design-css "\n" tokens/skin-css "\n" app-css))
    (io/delete-file generated-output true)
    (assoc result :outputs [output] :design-system :jp-go-digital)))

(defn hook
  {:shadow.build/stage :compile-finish}
  [build-state & _]
  (write!)
  build-state)

(defn -main [& _]
  (prn (select-keys (write!) [:outputs :bytes :warnings])))
